name: 💡 Feature Request
description: Suggest a new feature or enhancement for EchoGen.ai
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees:
  - Mr-Dark-debug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below with as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have checked the project roadmap
          required: true
        - label: This feature aligns with the project's goals
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: 💡 Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve?
      placeholder: Is your feature request related to a problem? Please describe...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💭 Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: A clear and concise description of any alternative solutions...

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my usage
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 📱 Platform
      description: Which platform(s) should this feature target?
      multiple: true
      options:
        - Android
        - iOS
        - Both
        - Web (future)
        - Desktop (future)
    validations:
      required: true

  - type: checkboxes
    id: feature-type
    attributes:
      label: 🏷️ Feature Type
      description: What type of feature is this?
      options:
        - label: UI/UX Enhancement
        - label: New Functionality
        - label: Performance Improvement
        - label: Integration/API
        - label: Accessibility
        - label: Developer Experience
        - label: Documentation

  - type: textarea
    id: user-story
    attributes:
      label: 👤 User Story
      description: Describe this feature as a user story
      placeholder: "As a [type of user], I want [goal] so that [benefit]"

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Mockups/Wireframes
      description: If applicable, add mockups, wireframes, or visual examples
      placeholder: Drag and drop images here or describe the visual design...

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I would like to work on this feature
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide feedback during development
