name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Build App Bundle
      run: flutter build appbundle --release
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        
    - name: Upload App Bundle artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-aab
        path: build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
      
    - name: Build iOS (no signing)
      run: flutter build ios --release --no-codesign
      
    - name: Create iOS archive
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace \
                   -scheme Runner \
                   -configuration Release \
                   -destination generic/platform=iOS \
                   -archivePath build/Runner.xcarchive \
                   archive
                   
    - name: Upload iOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-archive
        path: ios/build/Runner.xcarchive

  create-release:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download Android APK
      uses: actions/download-artifact@v4
      with:
        name: android-apk
        path: ./artifacts/
        
    - name: Download Android AAB
      uses: actions/download-artifact@v4
      with:
        name: android-aab
        path: ./artifacts/
        
    - name: Download iOS Archive
      uses: actions/download-artifact@v4
      with:
        name: ios-archive
        path: ./artifacts/
        
    - name: Get version from pubspec.yaml
      id: version
      run: |
        VERSION=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Release v${{ steps.version.outputs.version }}
        body: |
          ## What's New in v${{ steps.version.outputs.version }}
          
          ### 🎉 New Features
          - Background audio playback with notifications
          - Mini player across all screens
          - Custom cover art generation with ImageRouter
          - Centralized API key management
          - Enhanced loading page with helpful messages
          - Improved UI/UX across the app
          
          ### 🐛 Bug Fixes
          - Fixed model selection dropdown alignment issues
          - Improved audio playback reliability
          - Better error handling and user feedback
          
          ### 📱 Downloads
          - **Android APK**: Direct installation file
          - **Android AAB**: For Google Play Store
          - **iOS Archive**: For App Store distribution (requires signing)
          
          ---
          
          **Full Changelog**: https://github.com/echogenai/echogenai/compare/v0.1.0...v${{ steps.version.outputs.version }}
        files: |
          ./artifacts/app-release.apk
          ./artifacts/app-release.aab
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
